//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiReserva.Models
{
    using System;
    
    public partial class GetReserva_sp
    {
        public int idGrupoReserva { get; set; }
        public int idPersona { get; set; }
        public int idReserva { get; set; }
    }
}
