//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiReserva.Models
{
    using System;
    
    public partial class GetReservaById_sp
    {
        public int idReserva { get; set; }
        public int idCurso { get; set; }
        public byte idSemana { get; set; }
        public byte idDias { get; set; }
        public byte idHoraIn { get; set; }
        public byte idHoraF { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public int idGrupoReserva { get; set; }
        public int idPersona { get; set; }
        public int idReserva1 { get; set; }
    }
}
