//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiReserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCarrera()
        {
            this.tblEstudiante = new HashSet<tblEstudiante>();
        }
    
        public int idCarrera { get; set; }
        public int idTipoCarrera { get; set; }
        public string Carrera { get; set; }
    
        public virtual tblTipo tblTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstudiante> tblEstudiante { get; set; }
    }
}
