//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiReserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClase
    {
        public int idClase { get; set; }
        public int idDocente { get; set; }
        public int idCurso { get; set; }
        public byte idDias { get; set; }
        public byte idHoraIn { get; set; }
        public byte idHoraF { get; set; }
    
        public virtual tblCurso tblCurso { get; set; }
        public virtual tblDias tblDias { get; set; }
        public virtual tblDocente tblDocente { get; set; }
        public virtual tblHoras tblHoras { get; set; }
        public virtual tblHoras tblHoras1 { get; set; }
    }
}
