//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiReserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int idUsuario { get; set; }
        public string Pass { get; set; }
        public int idPersona { get; set; }
    
        public virtual tblPersona tblPersona { get; set; }
    }
}
